services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456

  notification-service:
    build: .
    container_name: notification-service
    restart: no
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://admin:123456@rabbitmq:5672
    command: ["npm", "run", "start:prod"]
    ports:
      - "3001:3000"
